---
title: "Listing 6 is bugged"
abstract: |
    This example document reports a bug about how Quarto numbered listings are rendered by latex.

    Since the bug is so fragile, I kept most of my original text. It's unrelated to the bug, but I wasn't brave enough to replace everything with Lorem Ipsum.
    Please ignore the content

        - Please ignore the content
        - Please ignore the content
        - Please ignore the content
        - Please ignore the content
        - Please ignore the content
  
    Since the bug is so fragile, I kept most of my original text. It's unrelated to the bug, but I wasn't brave enough to replace everything with Lorem Ipsum.
    Please ignore the content

# Specific options for the different output formats
# Latex macros need to be defined both for html and latex
format:
  pdf:
    keep-tex: true
    latex-clean: false
    pdf-engine: xelatex
    include-in-header:
        # Latex preamble: import packages, define macros, etc
        - text: |
            \def\sumi{{\frac{1}{n} \sum_{i=1}^n}}
---

# Listing 6 is bugged

**This document shows a bugged listing: @lst-bugged-listing. Ignore the rest of the text.** Please ignore the content

    - Please ignore the content
    - Please ignore the content
    - Please ignore the content
    - Please ignore the content
    - Please ignore the content

Since the bug is so fragile, I kept most of my original text. It's unrelated to the bug, but I wasn't brave enough to replace everything with Lorem Ipsum.
Please ignore the content
Since the bug is so fragile, I kept most of my original text. It's unrelated to the bug, but I wasn't brave enough to replace everything with Lorem Ipsum.
Please ignore the content
Since the bug is so fragile, I kept most of my original text. It's unrelated to the bug, but I wasn't brave enough to replace everything with Lorem Ipsum.
Please ignore the content


I wrote this document to illustrate what I believe to be the right solution to these issues.
This document does not aim to illustrate all of Quarto's syntax.
Please refer to [the Quarto documentation instead](https://quarto.org/docs/guide/).
In @sec-empirical-statistics, I present a simple example of a math theorem and proof.
In @sec-explanations, I explain how to solve the issues I encountered.

```{.yaml filename="document.qmd"}
---
format:
  html:
        - text: |
            <script>
            MathJax = {
                tex: {
                    tags: 'ams'  // should be 'ams', 'none', or 'all'
                }
            };
            </script>
---
```


I wrote this document to illustrate what I believe to be the right solution to these issues.
This document does not aim to illustrate all of Quarto's syntax.
Please refer to [the Quarto documentation instead](https://quarto.org/docs/guide/).
In @sec-empirical-statistics, I present a simple example of a math theorem and proof.
In @sec-explanations, I explain how to solve the issues I encountered.

## Empirical mean and variance {#sec-empirical-statistics}


Let $x_i$ be a dataset of values of $\mathbb{R}$. The empirical mean $m$ and variance $v$ are defined as:

\begin{align}
m   &= \sumi x_i \\
v   &= \sumi (x_i - m)^2    \label{def-empirical-variance}
\end{align}

::: {#thm-label}
The empirical variance can also be written as:

\begin{equation}
\label{eq:a}
v = (\sumi x_i^2) - m^2
\end{equation}
:::

```{.yaml filename="document.qmd"}
---
format:
  html:
        - text: |
            <script>
            MathJax = {
                tex: {
                    tags: 'ams'  // should be 'ams', 'none', or 'all'
                }
            };
            </script>
---
```

::: {.proof}
The proof is straightforward: we start from the original definition in eq.\eqref{def-empirical-variance} and expand the square.

\begin{align}
v   &= \sumi (x_i - m)^2 \\
    &= \sumi (x_i^2 - 2 x_i m + m^2) \\
    &= (\sumi x_i^2) - 2 (\sumi x_i) m + (\sumi 1) m^2 \\
    &= (\sumi x_i^2) - 2 m m + 1 m^2 \\
    &= (\sumi x_i^2) - m^2
\end{align}

This concludes the proof: we have indeed established the correctness of eq.\eqref{eq:a}.
:::

## Explanations {#sec-explanations}

### Numbering equations in HTML

In a HTML document, equations are rendered by [MathJax](https://www.mathjax.org/).
By default, MathJax does not number equations.
In order to number equations, we need to modify the MathJax configuration.
A simple self-contained solution is to modify the yaml preamble of the qmd file.

Please note, if your preamble becomes too complex, you can export it to a separate file.

```{.yaml filename="document.qmd"}
---
format:
  html:
        - text: |
            <script>
            MathJax = {
                tex: {
                    tags: 'ams'  // should be 'ams', 'none', or 'all'
                }
            };
            </script>
---
```

```{.yaml filename="document.qmd"}
---
format:
  html:
        - text: |
            <script>
            MathJax = {
                tex: {
                    tags: 'ams'  // should be 'ams', 'none', or 'all'
                }
            };
            </script>
---
```

### Macros

Macros are necessary when writing complex math, both to simplify the source code and improve writing speed.
It is tricky to define macros in Quarto.
My solution is to define macros in the yaml preamble, hard-coding them in the premable of the html and tex file.

Please note that macros need to be wrote twice: once for html, once for tex.
This approach also makes the macros invisible for Quarto.

```{.yaml filename="document.qmd"}
---
format:
    pdf:
        include-in-header:
            - text: |
                \def\sumi{{\frac{1}{n} \sum_{i=1}^n}}
    html:
        include-before-body:
            - text: |
                $$
                    \def\sumi{{\frac{1}{n} \sum_{i=1}^n}}
                $$

---
```

### Equation cross-references

For equation cross-referencing, it is necessary to use the Latex `\label{label}` and `\eqref{label}` syntax,
instead of the Quarto `@label` syntax. For example:

```latex
\begin{equation}
    1 + 1 = 2
\label{the_equation}
\end{equation}

Eq.\eqref{the_equation} is much deeper than it appears.
```

Please note that figure and section cross-referencing should use Quarto syntax.

Also note that, if you do not number all equations, then you need to further add a `\tag` command.
Otherwise, in HTML output, MathJax does not label the equation. The eqref then produces a `???` href to the correct equation.
For example:

```{#lst-bugged-listing .latex lst-cap="This listing is bugged"}
In this listing, the line marking
the end of the listing is not rendered
in the right position.

$$ This line is inside the listing $$
```

This text is outside the listing

The line above mixes:

- a normal text line: `This text is outside the listing`
- a line from inside the code listing: `$$ This line is inside the listing $$`{.yaml}

```{#lst-bugged-listing2 .latex lst-cap="This listing is not bugged"}
In this listing, the line marking
the end of the listing is not rendered
in the right position.

$$ This line is inside the listing $$
```

Some text outside the listing.